// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Entities;

public partial class Product
{
    public int Id { get; set; }
    [Required]
    public string Name { get; set; }

    public int CategoryId { get; set; }

    public string Description { get; set; }
    [Required]
    public double Price { get; set; }
    [Required]
    public string ImgUrl { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}